# https://api-platform.com/docs/core/configuration/

api_platform:
    # The title of the API.
    title: 'Majority Judgment API'

    # The description of the API.
    description: |
        This is a **deliberation service** using **majority judgment** polling.
        It's **libre software** made and maintained by [MieuxVoter.fr](https://mieuxvoter.fr).
        You're browsing the API documentation.

    # The version of the API.
    version: '0.0.0-dev'

    # Set this to false if you want Webby to disappear.
    show_webby: false

    # The shenanigans
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    
    enable_profiler: true
    
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header