<?php

// generated by `make:user:msgphp`
// this configuration may be merged into your existing application configuration

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use function Symfony\Component\DependencyInjection\Loader\Configurator\ref;

return function (ContainerConfigurator $container) {
    $container->extension('msgphp_user', array (
  'class_mapping' => 
  array (
    'MsgPhp\\User\\Credential\\Credential' => 'MsgPhp\\User\\Credential\\EmailPassword',
    'MsgPhp\\User\\Role' => 'App\\Entity\\Role',
    'MsgPhp\\User\\UserRole' => 'App\\Entity\\UserRole',
  ),
  'role_providers' => 
  array (
    'default' => 
    array (
      0 => 'ROLE_USER',
    ),
    0 => 'MsgPhp\\User\\Role\\UserRoleProvider',
  ),
));

    $container->services()
        ->defaults()
            ->private()
            ->autoconfigure()
            ->autowire()

        ->set(App\Console\ClassContextElementFactory::class)
        ->alias(MsgPhp\Domain\Infrastructure\Console\Context\ClassContextElementFactory::class, App\Console\ClassContextElementFactory::class)
    ;
};
