# You may need to run
#     symfony server:ca:install
# in order to get HTTPS in localhost dev
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'User-Agent']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
