# Configuration file for Gitlab's Continuous Integration
# https://docs.gitlab.com/ee/ci/yaml/
test:
  # Get docker image (see https://docs.gitlab.com/ee/ci/docker/using_docker_images.html)
  # Note; with the php:latest we don't use debian php packages. Don't try to install them.
  image: php:latest

  cache:
    paths:
      - vendor/

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  before_script:
    - apt-get update
    - apt-get install -y unzip
    - apt-get install -y fortunes

    # Install xdebug for code coverage
    # We cannot use docker-php-ext-install here
    - pecl install xdebug
    - echo "zend_extension=xdebug.so" >> /usr/local/etc/php/php.ini
    - echo "xdebug.coverage_enable=1" >> /usr/local/etc/php/php.ini

    # Install Composer
    # Remember, we can't use the php packages from debian repos in this image
    #    - apt-get install composer
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    # Install PHP Vendors and autoloading goodies
    - COMPOSER_MEMORY_LIMIT=4G php composer.phar install --no-interaction
#    - docker-php-ext-install pdo_sqlite


  # These scripts are also run as root
  script:
    # Configure the feature suite with the defaults
    - cp behat.yml.dist behat.yml
    # Run the feature suite
    - vendor/bin/behat -vv --tags=~noci

  # We've also set this using gitlab's CI Settings UI
#  coverage: '/^\s*Lines:\s*(\d+\.\d+)%/'
