# Example usage:
#   docker-compose up --build --detach
#   docker-compose down

# Careful: MV server has an outdated version of docker-compose (3.4 works).
version: "3.4"

services:
  php:
    container_name: oas
    build:
      context: .
      target: symfony_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    healthcheck:
      interval: 3600s
      timeout: 30s
      retries: 2
      start_period: 30s
    volumes:
      - ./:/srv/app:rw,cached
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      # - /srv/app/var/
      # - /srv/app/var/cache/
      # - /srv/app/var/logs/
      # - /srv/app/var/sessions/
    environment:
      - SYMFONY_VERSION
    depends_on:
      - db

  nginx:
    container_name: oas_nginx
    build:
      context: .
      target: symfony_nginx
    depends_on:
      - php
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/srv/app/public:ro
    ports:
      - "80:80"

  # This HTTP/2 proxy is not secure: it should only be used in dev
  h2-proxy:
    build:
      context: .
      target: symfony_h2-proxy
    depends_on:
      - nginx
    volumes:
      - ./docker/h2-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "443:443"

  # Perhaps switch to postgres at some point?
  db:
    container_name: oas_db
    image: mariadb:10.5.5
    env_file:
      - .env
      - .env.local
      #- .env.prod.local
    environment:
      # Best not edit secrets in here ; edit .env.local after creating it from .env
      - MYSQL_DATABASE=${MVOAS_MYSQL_DATABASE:-limaju}
      - MYSQL_USER=${MVOAS_MYSQL_USERNAME:-limaju}
      - MYSQL_PASSWORD=${MVOAS_MYSQL_PASSWORD:-limaju}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    # If we need this, let's mount it somewhere other than ./var (conflicts with symfony)
    # Perhaps we do need to mount _some_ volumes to preserve the database.
    # I noticed the database being reset last time I built.
    #volumes:
    #  - ./var/db/data:/var/lib/mysql:rw
    #ports:
    #  - "3308:3306"


  