# Example usage:
#   docker-compose up
#   docker-compose up --build --detach
#   docker-compose down

# Careful: MV server has an outdated version of docker-compose (3.4 works).
# You can safely ignore the warning about this attribute being obsolete, it's benign.
#version: "3.4"

services:
  php:
    container_name: mvoas
    build:
      context: .
      target: symfony_php_dev
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
        #GIT_TOKEN: "${GIT_TOKEN:-}"
    restart: unless-stopped
    volumes:
      - ./:/srv/app:rw,cached
    environment:
      - SYMFONY_VERSION
    depends_on:
      - db

  # Perhaps switch to postgres at some point?
  db:
    container_name: mvoas_db
    image: mariadb:12.2
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true
      - path: ./.env.local
        required: false
      - path: ./.env.prod.local
        required: false
    environment:
      # Best not write secrets in here ; edit .env.local after creating it from .env, or use real env vars.
      - MYSQL_DATABASE=${MVOAS_MYSQL_DATABASE:?error}
      - MYSQL_USER=${MVOAS_MYSQL_USERNAME:?error}
      - MYSQL_PASSWORD=${MVOAS_MYSQL_PASSWORD:?error}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    # If you need a filesystem volume, best mount it somewhere other than ./var (conflicts with symfony).
    #volumes:
    #  - ./var/db/data:/var/lib/mysql:rw
    # Named volumes work just fine.
    volumes:
      - mv_oas_db:/var/lib/mysql:rw
    #ports:
    #  - "3308:3306"

  nginx:
    container_name: mvoas_nginx
    build:
      context: .
      target: symfony_nginx
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/srv/app/public:ro
    ports:
      - "80:80"

  # This HTTP/2 proxy is not secure: it should only be used in dev
  # FIXME: remove this from here and use compose overrides instead
  h2-proxy:
    build:
      context: .
      target: symfony_h2-proxy
    depends_on:
      - nginx
    volumes:
      - ./docker/h2-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "443:443"

volumes:
  mv_oas_db:
  