# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        public: true
        resource: '../src/*'
        exclude:
            - '../src/{Features,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
            - '../src/Tally/Output'

    # Override the test client to get pretty responses for CLI, and perhaps store some config like URL prefixes.
    test.client:
        # Try removing the public: true for a very confusing error message about framework.test
        public: true
        class: App\Features\ApiTesterClient


    # The services we need in the feature suite
    App\Features\:
        public: true
        resource: '../src/Features/{Actors.php}'

    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Override to make public, only because of the test-suite.  Remove this if you can.
    MsgPhp\User\Infrastructure\Doctrine\Repository\UserRepository:
        public: true
        arguments:
            - "App\\Entity\\User"
            - "@doctrine.orm.default_entity_manager"
            - "credential.email"

    # Who doesn't need Twig in translations strings?
    App\Translator\TwiggyTranslator:
        decorates: translator
        arguments:
            # Translation domains to enable Twig for (other domains _should_ behave like usual)
            - ['messages', 'features', '', ]
            # Pass the old service as an argument, it has all the I18N config
            # This service id only exists because we're decorating the translator
            - '@App\Translator\TwiggyTranslator.inner'
            # Twig also has the extensions and global vars available
            - "@twig"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
