
# To get available options:
# java -jar ./openapi-generator-cli.jar config-help -g javascript

projectName: "mv-api-client-lib"
projectDescription: |
  A javascript client for the Majority Judgment OpenAPI of MieuxVoter.
  Sandbox: https://oas.mieuxvoter.fr
  This library was generated automatically, best not edit it directly.
usePromises: true
licenseName: MIT
invokerPackage: MieuxVoter
# Commented because it causes trouble for @id and @type and @context (extra @)
#emitModelMethods: true
files:
  LICENSE: {}
#  README.md: {}
#  api_interfaces.mustache:
#    templateType: API
#    destinationFilename: Interface.kt
